// src/utils/data.js

export const questions = [
    {
      id: 1,
      image: '/images/farmrio-image1.png',
      responseQuestion1: 'O que você achou do nosso atendimento?',
      responses1: ['Excelente', 'Péssimo'],
      responseQuestion2: 'A variedade de produtos na loja física atendeu suas expectativas?',
      responses2: ['Sim', 'Não'],
      responseQuestion3: 'Você encontrou o que procurava em nossa loja física?',
      responses3: ['Sim', 'Não'],
    },
    {
      id: 2,
      image: '/images/farmrio-image2.png',
      responseQuestion1: 'Os produtos atendem suas expectativas de qualidade?',
      responses1: ['Sim', 'Não'],
      responseQuestion2: 'Você encontrou o que procurava em nossa loja?',
      responses2: ['Sim', 'Não'],
      responseQuestion3: 'Os produtos têm um bom custo-benefício?',
      responses3: ['Sim', 'Não'],
    },
    {
      id: 3,
      image: '/images/farmrio-image3.png',
      responseQuestion1: 'A navegação no site é fácil?',
      responses1: ['Sim', 'Não'],
      responseQuestion2: 'O processo de compra foi satisfatório?',
      responses2: ['Sim', 'Não'],
      responseQuestion3: 'Você teve algum problema com a entrega?',
      responses3: ['Sim', 'Não'],
    },
    {
      id: 4,
      image: '/images/farmrio-image4.png',
      responseQuestion1: 'O que mais você gosta na Farm Rio?',
      responses1: ['Qualidade', 'Variedade'],
      responseQuestion2: 'O que menos você gosta na Farm Rio?',
      responses2: ['Preço', 'Variedade'],
      responseQuestion3: 'Você considera a Farm Rio uma marca sustentável?',
      responses3: ['Sim', 'Não'],
    },
    {
      id: 5,
      image: '/images/presente.png',
      responseQuestion1: 'Os preços são justos?',
      responses1: ['Sim', 'Não'],
      responseQuestion2: 'Você aproveitou alguma promoção?',
      responses2: ['Sim', 'Não'],
      responseQuestion3: 'Você costuma recomendar a Farm Rio para amigos?',
      responses3: ['Sim', 'Não'],
    },
  ];
